export const ActionTypes = {
  SET_CATEGORY: "SET_CATEGORY",
  SELECTED_CATEGORY: "SELECTED_CATEGORY",
  FETCH_CATEGORY: "FETCH_CATEGORY",

  SET_RESULT: "SET_RESULT",
  SELECTED_RESULT: "SELECTED_RESULT",

  LOGIN_START: "LOGIN_START",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
};
